In [1]:
import requests
import pandas as pd

print('Environment is ready!')

Environment is ready!

In [2]:
url = "https://api.coingecko.com/api/v3/coins/markets"

params = {
    "vs_currency": "usd",
    "order": "market_cap_desc",
    "per_page": 10,
    "page": 1,
    "sparkline": False 
}

response = requests.get(url, params=params, timeout=30)

print(response.status_code)

200

In [3]:
data = response.json()

In [4]:
data

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'current_price': 64076,
  'market_cap': 1285945024366,
  'market_cap_rank': 1,
  'fully_diluted_valuation': 1285946434073,
  'total_volume': 20417791024,
  'high_24h': 65317,
  'low_24h': 63771,
  'price_change_24h': -913.113217792612,
  'price_change_percentage_24h': -1.7,
  'market_cap_change_24h': -18271911180.725586,
  'market_cap_change_percentage_24h': -1.40099,
  'circulating_supply': 20068553.0,
  'total_supply': 20068575.0,
  'max_supply': 21000000.0,
  'ath': 126080,
  'ath_change_percentage': -49.17808,
  'ath_date': '2025-10-06T10:57:42.000Z',
  'atl': 67.81,
  'atl_change_percentage': 94395.14694,
  'atl_date': '2013-07-05T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-08-11T03:37:20.000Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'current_price': 1878.75,
  'market_cap': 226738675664,
  'market_cap_rank': 2,
  'fully_diluted_valuation': 226738675664,
  'total_volume': 7009662322,
  'high_24h': 1928.94,
  'low_24h': 1867.61,
  'price_change_24h': -40.03743174700594,
  'price_change_percentage_24h': -2.3,
  'market_cap_change_24h': -4825042193.290222,
  'market_cap_change_percentage_24h': -2.08368,
  'circulating_supply': 120682035.68761347,
  'total_supply': 120682035.6876134,
  'max_supply': None,
  'ath': 4946.05,
  'ath_change_percentage': -62.01502,
  'ath_date': '2025-08-24T11:21:03.000Z',
  'atl': 0.432979,
  'atl_change_percentage': 433813.86282,
  'atl_date': '2015-10-19T16:00:00.000Z',
  'roi': {'times': 38.20114588500874,
   'currency': 'btc',
   'percentage': 3820.1145885008746},
  'last_updated': '2026-08-11T03:37:20.000Z'},
 {'id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'image': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  'current_price': 0.999123,
  'market_cap': 183090218119,
  'market_cap_rank': 3,
  'fully_diluted_valuation': 188552514871,
  'total_volume': 32917405107,
  'high_24h': 0.999842,
  'low_24h': 0.998973,
  'price_change_24h': -0.000225895976225687,
  'price_change_percentage_24h': 0.0,
  'market_cap_change_24h': -36472101.503845215,
  'market_cap_change_percentage_24h': -0.01992,
  'circulating_supply': 183245941051.28,
  'total_supply': 188712883627.4062,
  'max_supply': None,
  'ath': 1.32,
  'ath_change_percentage': -24.48591,
  'ath_date': '2018-07-23T16:00:00.000Z',
  'atl': 0.572521,
  'atl_change_percentage': 74.51296,
  'atl_date': '2015-03-01T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-08-11T03:37:20.000Z'},
 {'id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'image': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  'current_price': 599.83,
  'market_cap': 79877019560,
  'market_cap_rank': 4,
  'fully_diluted_valuation': 79877018709,
  'total_volume': 512205854,
  'high_24h': 606.0,
  'low_24h': 597.29,
  'price_change_24h': -2.0997937510313704,
  'price_change_percentage_24h': -0.6,
  'market_cap_change_24h': -278230424.4975281,
  'market_cap_change_percentage_24h': -0.34711,
  'circulating_supply': 133164295.31,
  'total_supply': 133164293.08,
  'max_supply': 200000000.0,
  'ath': 1369.99,
  'ath_change_percentage': -56.21672,
  'ath_date': '2025-10-13T00:41:24.000Z',
  'atl': 0.0398177,
  'atl_change_percentage': 1506333.68913,
  'atl_date': '2017-10-18T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-08-11T03:37:20.000Z'},
 {'id': 'usd-coin',
  'symbol': 'usdc',
  'name': 'USDC',
  'image': 'https://coin-images.coingecko.com/coins/images/6319/large/USDC.png?1769615602',
  'current_price': 0.999616,
  'market_cap': 72224423782,
  'market_cap_rank': 5,
  'fully_diluted_valuation': 72219476624,
  'total_volume': 8240571576,
  'high_24h': 1.0,
  'low_24h': 0.999435,
  'price_change_24h': -4.8463191422377e-05,
  'price_change_percentage_24h': 0.0,
  'market_cap_change_24h': 77914140,
  'market_cap_change_percentage_24h': 0.10799,
  'circulating_supply': 72249714663.12177,
  'total_supply': 72237107334.14743,
  'max_supply': None,
  'ath': 1.043,
  'ath_change_percentage': -4.20226,
  'ath_date': '2018-11-14T16:00:00.000Z',
  'atl': 0.877647,
  'atl_change_percentage': 13.89727,
  'atl_date': '2023-03-11T00:02:13.000Z',
  'roi': None,
  'last_updated': '2026-08-11T03:37:20.000Z'},
 {'id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'image': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  'current_price': 1.013,
  'market_cap': 63327234863,
  'market_cap_rank': 6,
  'fully_diluted_valuation': 101255118073,
  'total_volume': 988875287,
  'high_24h': 1.039,
  'low_24h': 1.008,
  'price_change_24h': -0.01907135877264121,
  'price_change_percentage_24h': -2.1,
  'market_cap_change_24h': -1194773559.8239365,
  'market_cap_change_percentage_24h': -1.85173,
  'circulating_supply': 62533271955.0,
  'total_supply': 99985635707.0,
  'max_supply': 100000000000.0,
  'ath': 3.65,
  'ath_change_percentage': -72.22637,
  'ath_date': '2025-07-17T19:40:53.000Z',
  'atl': 0.00268621,
  'atl_change_percentage': 37601.17574,
  'atl_date': '2014-05-21T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-08-11T03:37:20.000Z'},
 {'id': 'solana',
  'symbol': 'sol',
  'name': 'Solana',
  'image': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756',
  'current_price': 76.08,
  'market_cap': 44312332464,
  'market_cap_rank': 7,
  'fully_diluted_valuation': 48080181334,
  'total_volume': 1334640618,
  'high_24h': 77.07,
  'low_24h': 75.57,
  'price_change_24h': -0.5006441625416045,
  'price_change_percentage_24h': -0.9,
  'market_cap_change_24h': -269699057.5904007,
  'market_cap_change_percentage_24h': -0.60495,
  'circulating_supply': 582481816.1247106,
  'total_supply': 632009858.2513136,
  'max_supply': None,
  'ath': 293.31,
  'ath_change_percentage': -74.06206,
  'ath_date': '2025-01-19T03:15:27.000Z',
  'atl': 0.500801,
  'atl_change_percentage': 15091.47384,
  'atl_date': '2020-05-11T11:35:23.000Z',
  'roi': None,
  'last_updated': '2026-08-11T03:37:20.000Z'},
 {'id': 'tron',
  'symbol': 'trx',
  'name': 'TRON',
  'image': 'https://coin-images.coingecko.com/coins/images/1094/large/photo_2026-04-13_09-59-16.png?1776048311',
  'current_price': 0.331001,
  'market_cap': 31410105051,
  'market_cap_rank': 8,
  'fully_diluted_valuation': 31410354783,
  'total_volume': 373327404,
  'high_24h': 0.331643,
  'low_24h': 0.329494,
  'price_change_24h': 0.001035,
  'price_change_percentage_24h': 0.2,
  'market_cap_change_24h': 98463381,
  'market_cap_change_percentage_24h': 0.31446,
  'circulating_supply': 94897630288.19649,
  'total_supply': 94898358646.86598,
  'max_supply': None,
  'ath': 0.431288,
  'ath_change_percentage': -23.25298,
  'ath_date': '2024-12-03T16:10:40.000Z',
  'atl': 0.00180434,
  'atl_change_percentage': 18244.69435,
  'atl_date': '2017-11-11T16:00:00.000Z',
  'roi': {'times': 173.1728703050978,
   'currency': 'usd',
   'percentage': 17317.28703050978},
  'last_updated': '2026-08-11T03:37:20.000Z'},
 {'id': 'figure-heloc',
  'symbol': 'figr_heloc',
  'name': 'Figure Heloc',
  'image': 'https://coin-images.coingecko.com/coins/images/68480/large/figure.png?1755863954',
  'current_price': 1.003,
  'market_cap': 21140202274,
  'market_cap_rank': 9,
  'fully_diluted_valuation': 21140202274,
  'total_volume': 53014149,
  'high_24h': 1.041,
  'low_24h': 1.002,
  'price_change_24h': None,
  'price_change_percentage_24h': 0.2,
  'market_cap_change_24h': None,
  'market_cap_change_percentage_24h': None,
  'circulating_supply': 21082493891.176,
  'total_supply': 21082493891.176,
  'max_supply': None,
  'ath': 1.061,
  'ath_change_percentage': -5.44703,
  'ath_date': '2026-08-03T14:19:20.000Z',
  'atl': 0.155357,
  'atl_change_percentage': 545.46279,
  'atl_date': '2025-10-31T06:27:24.000Z',
  'roi': None,
  'last_updated': '2026-08-11T03:37:20.000Z'},
 {'id': 'hyperliquid',
  'symbol': 'hype',
  'name': 'Hyperliquid',
  'image': 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300',
  'current_price': 55.26,
  'market_cap': 12292761640,
  'market_cap_rank': 10,
  'fully_diluted_valuation': 55252743222,
  'total_volume': 247953125,
  'high_24h': 56.02,
  'low_24h': 53.95,
  'price_change_24h': 1.16,
  'price_change_percentage_24h': 1.7,
  'market_cap_change_24h': 258404656,
  'market_cap_change_percentage_24h': 2.14722,
  'circulating_supply': 222445714.07414138,
  'total_supply': 955307079.4341414,
  'max_supply': 1000000000.0,
  'ath': 76.87,
  'ath_change_percentage': -28.10703,
  'ath_date': '2026-06-16T13:00:30.000Z',
  'atl': 3.81,
  'atl_change_percentage': 1350.91263,
  'atl_date': '2024-11-29T01:30:30.000Z',
  'roi': None,
  'last_updated': '2026-08-11T03:37:20.000Z'}]

In [5]:
type(data)

list

In [6]:
len(data)

10

In [7]:
data[0]

{'id': 'bitcoin',
 'symbol': 'btc',
 'name': 'Bitcoin',
 'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
 'current_price': 64076,
 'market_cap': 1285945024366,
 'market_cap_rank': 1,
 'fully_diluted_valuation': 1285946434073,
 'total_volume': 20417791024,
 'high_24h': 65317,
 'low_24h': 63771,
 'price_change_24h': -913.113217792612,
 'price_change_percentage_24h': -1.7,
 'market_cap_change_24h': -18271911180.725586,
 'market_cap_change_percentage_24h': -1.40099,
 'circulating_supply': 20068553.0,
 'total_supply': 20068575.0,
 'max_supply': 21000000.0,
 'ath': 126080,
 'ath_change_percentage': -49.17808,
 'ath_date': '2025-10-06T10:57:42.000Z',
 'atl': 67.81,
 'atl_change_percentage': 94395.14694,
 'atl_date': '2013-07-05T16:00:00.000Z',
 'roi': None,
 'last_updated': '2026-08-11T03:37:20.000Z'}

In [8]:
type(data[0])

dict

In [9]:
data[0]["name"]

'Bitcoin'

In [10]:
data[0]["current_price"]

64076

In [11]:
data[1]["name"]

'Ethereum'

In [12]:
data = response.json()

In [13]:
data

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'current_price': 64076,
  'market_cap': 1285945024366,
  'market_cap_rank': 1,
  'fully_diluted_valuation': 1285946434073,
  'total_volume': 20417791024,
  'high_24h': 65317,
  'low_24h': 63771,
  'price_change_24h': -913.113217792612,
  'price_change_percentage_24h': -1.7,
  'market_cap_change_24h': -18271911180.725586,
  'market_cap_change_percentage_24h': -1.40099,
  'circulating_supply': 20068553.0,
  'total_supply': 20068575.0,
  'max_supply': 21000000.0,
  'ath': 126080,
  'ath_change_percentage': -49.17808,
  'ath_date': '2025-10-06T10:57:42.000Z',
  'atl': 67.81,
  'atl_change_percentage': 94395.14694,
  'atl_date': '2013-07-05T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-08-11T03:37:20.000Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'current_price': 1878.75,
  'market_cap': 226738675664,
  'market_cap_rank': 2,
  'fully_diluted_valuation': 226738675664,
  'total_volume': 7009662322,
  'high_24h': 1928.94,
  'low_24h': 1867.61,
  'price_change_24h': -40.03743174700594,
  'price_change_percentage_24h': -2.3,
  'market_cap_change_24h': -4825042193.290222,
  'market_cap_change_percentage_24h': -2.08368,
  'circulating_supply': 120682035.68761347,
  'total_supply': 120682035.6876134,
  'max_supply': None,
  'ath': 4946.05,
  'ath_change_percentage': -62.01502,
  'ath_date': '2025-08-24T11:21:03.000Z',
  'atl': 0.432979,
  'atl_change_percentage': 433813.86282,
  'atl_date': '2015-10-19T16:00:00.000Z',
  'roi': {'times': 38.20114588500874,
   'currency': 'btc',
   'percentage': 3820.1145885008746},
  'last_updated': '2026-08-11T03:37:20.000Z'},
 {'id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'image': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  'current_price': 0.999123,
  'market_cap': 183090218119,
  'market_cap_rank': 3,
  'fully_diluted_valuation': 188552514871,
  'total_volume': 32917405107,
  'high_24h': 0.999842,
  'low_24h': 0.998973,
  'price_change_24h': -0.000225895976225687,
  'price_change_percentage_24h': 0.0,
  'market_cap_change_24h': -36472101.503845215,
  'market_cap_change_percentage_24h': -0.01992,
  'circulating_supply': 183245941051.28,
  'total_supply': 188712883627.4062,
  'max_supply': None,
  'ath': 1.32,
  'ath_change_percentage': -24.48591,
  'ath_date': '2018-07-23T16:00:00.000Z',
  'atl': 0.572521,
  'atl_change_percentage': 74.51296,
  'atl_date': '2015-03-01T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-08-11T03:37:20.000Z'},
 {'id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'image': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  'current_price': 599.83,
  'market_cap': 79877019560,
  'market_cap_rank': 4,
  'fully_diluted_valuation': 79877018709,
  'total_volume': 512205854,
  'high_24h': 606.0,
  'low_24h': 597.29,
  'price_change_24h': -2.0997937510313704,
  'price_change_percentage_24h': -0.6,
  'market_cap_change_24h': -278230424.4975281,
  'market_cap_change_percentage_24h': -0.34711,
  'circulating_supply': 133164295.31,
  'total_supply': 133164293.08,
  'max_supply': 200000000.0,
  'ath': 1369.99,
  'ath_change_percentage': -56.21672,
  'ath_date': '2025-10-13T00:41:24.000Z',
  'atl': 0.0398177,
  'atl_change_percentage': 1506333.68913,
  'atl_date': '2017-10-18T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-08-11T03:37:20.000Z'},
 {'id': 'usd-coin',
  'symbol': 'usdc',
  'name': 'USDC',
  'image': 'https://coin-images.coingecko.com/coins/images/6319/large/USDC.png?1769615602',
  'current_price': 0.999616,
  'market_cap': 72224423782,
  'market_cap_rank': 5,
  'fully_diluted_valuation': 72219476624,
  'total_volume': 8240571576,
  'high_24h': 1.0,
  'low_24h': 0.999435,
  'price_change_24h': -4.8463191422377e-05,
  'price_change_percentage_24h': 0.0,
  'market_cap_change_24h': 77914140,
  'market_cap_change_percentage_24h': 0.10799,
  'circulating_supply': 72249714663.12177,
  'total_supply': 72237107334.14743,
  'max_supply': None,
  'ath': 1.043,
  'ath_change_percentage': -4.20226,
  'ath_date': '2018-11-14T16:00:00.000Z',
  'atl': 0.877647,
  'atl_change_percentage': 13.89727,
  'atl_date': '2023-03-11T00:02:13.000Z',
  'roi': None,
  'last_updated': '2026-08-11T03:37:20.000Z'},
 {'id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'image': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  'current_price': 1.013,
  'market_cap': 63327234863,
  'market_cap_rank': 6,
  'fully_diluted_valuation': 101255118073,
  'total_volume': 988875287,
  'high_24h': 1.039,
  'low_24h': 1.008,
  'price_change_24h': -0.01907135877264121,
  'price_change_percentage_24h': -2.1,
  'market_cap_change_24h': -1194773559.8239365,
  'market_cap_change_percentage_24h': -1.85173,
  'circulating_supply': 62533271955.0,
  'total_supply': 99985635707.0,
  'max_supply': 100000000000.0,
  'ath': 3.65,
  'ath_change_percentage': -72.22637,
  'ath_date': '2025-07-17T19:40:53.000Z',
  'atl': 0.00268621,
  'atl_change_percentage': 37601.17574,
  'atl_date': '2014-05-21T16:00:00.000Z',
  'roi': None,
  'last_updated': '2026-08-11T03:37:20.000Z'},
 {'id': 'solana',
  'symbol': 'sol',
  'name': 'Solana',
  'image': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756',
  'current_price': 76.08,
  'market_cap': 44312332464,
  'market_cap_rank': 7,
  'fully_diluted_valuation': 48080181334,
  'total_volume': 1334640618,
  'high_24h': 77.07,
  'low_24h': 75.57,
  'price_change_24h': -0.5006441625416045,
  'price_change_percentage_24h': -0.9,
  'market_cap_change_24h': -269699057.5904007,
  'market_cap_change_percentage_24h': -0.60495,
  'circulating_supply': 582481816.1247106,
  'total_supply': 632009858.2513136,
  'max_supply': None,
  'ath': 293.31,
  'ath_change_percentage': -74.06206,
  'ath_date': '2025-01-19T03:15:27.000Z',
  'atl': 0.500801,
  'atl_change_percentage': 15091.47384,
  'atl_date': '2020-05-11T11:35:23.000Z',
  'roi': None,
  'last_updated': '2026-08-11T03:37:20.000Z'},
 {'id': 'tron',
  'symbol': 'trx',
  'name': 'TRON',
  'image': 'https://coin-images.coingecko.com/coins/images/1094/large/photo_2026-04-13_09-59-16.png?1776048311',
  'current_price': 0.331001,
  'market_cap': 31410105051,
  'market_cap_rank': 8,
  'fully_diluted_valuation': 31410354783,
  'total_volume': 373327404,
  'high_24h': 0.331643,
  'low_24h': 0.329494,
  'price_change_24h': 0.001035,
  'price_change_percentage_24h': 0.2,
  'market_cap_change_24h': 98463381,
  'market_cap_change_percentage_24h': 0.31446,
  'circulating_supply': 94897630288.19649,
  'total_supply': 94898358646.86598,
  'max_supply': None,
  'ath': 0.431288,
  'ath_change_percentage': -23.25298,
  'ath_date': '2024-12-03T16:10:40.000Z',
  'atl': 0.00180434,
  'atl_change_percentage': 18244.69435,
  'atl_date': '2017-11-11T16:00:00.000Z',
  'roi': {'times': 173.1728703050978,
   'currency': 'usd',
   'percentage': 17317.28703050978},
  'last_updated': '2026-08-11T03:37:20.000Z'},
 {'id': 'figure-heloc',
  'symbol': 'figr_heloc',
  'name': 'Figure Heloc',
  'image': 'https://coin-images.coingecko.com/coins/images/68480/large/figure.png?1755863954',
  'current_price': 1.003,
  'market_cap': 21140202274,
  'market_cap_rank': 9,
  'fully_diluted_valuation': 21140202274,
  'total_volume': 53014149,
  'high_24h': 1.041,
  'low_24h': 1.002,
  'price_change_24h': None,
  'price_change_percentage_24h': 0.2,
  'market_cap_change_24h': None,
  'market_cap_change_percentage_24h': None,
  'circulating_supply': 21082493891.176,
  'total_supply': 21082493891.176,
  'max_supply': None,
  'ath': 1.061,
  'ath_change_percentage': -5.44703,
  'ath_date': '2026-08-03T14:19:20.000Z',
  'atl': 0.155357,
  'atl_change_percentage': 545.46279,
  'atl_date': '2025-10-31T06:27:24.000Z',
  'roi': None,
  'last_updated': '2026-08-11T03:37:20.000Z'},
 {'id': 'hyperliquid',
  'symbol': 'hype',
  'name': 'Hyperliquid',
  'image': 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300',
  'current_price': 55.26,
  'market_cap': 12292761640,
  'market_cap_rank': 10,
  'fully_diluted_valuation': 55252743222,
  'total_volume': 247953125,
  'high_24h': 56.02,
  'low_24h': 53.95,
  'price_change_24h': 1.16,
  'price_change_percentage_24h': 1.7,
  'market_cap_change_24h': 258404656,
  'market_cap_change_percentage_24h': 2.14722,
  'circulating_supply': 222445714.07414138,
  'total_supply': 955307079.4341414,
  'max_supply': 1000000000.0,
  'ath': 76.87,
  'ath_change_percentage': -28.10703,
  'ath_date': '2026-06-16T13:00:30.000Z',
  'atl': 3.81,
  'atl_change_percentage': 1350.91263,
  'atl_date': '2024-11-29T01:30:30.000Z',
  'roi': None,
  'last_updated': '2026-08-11T03:37:20.000Z'}]

In [14]:
df = pd.DataFrame(data)

In [15]:
df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,64076.000000,1285945024366,1,1285946434073,20417791024,65317.000000,...,2.006858e+07,2.100000e+07,126080.000000,-49.17808,2025-10-06T10:57:42.000Z,67.810000,9.439515e+04,2013-07-05T16:00:00.000Z,None,2026-08-11T03:37:20.000Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,1878.750000,226738675664,2,226738675664,7009662322,1928.940000,...,1.206820e+08,NaN,4946.050000,-62.01502,2025-08-24T11:21:03.000Z,0.432979,4.338139e+05,2015-10-19T16:00:00.000Z,"{'times': 38.20114588500874, 'currency': 'btc'...",2026-08-11T03:37:20.000Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999123,183090218119,3,188552514871,32917405107,0.999842,...,1.887129e+11,NaN,1.320000,-24.48591,2018-07-23T16:00:00.000Z,0.572521,7.451296e+01,2015-03-01T16:00:00.000Z,None,2026-08-11T03:37:20.000Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,599.830000,79877019560,4,79877018709,512205854,606.000000,...,1.331643e+08,2.000000e+08,1369.990000,-56.21672,2025-10-13T00:41:24.000Z,0.039818,1.506334e+06,2017-10-18T16:00:00.000Z,None,2026-08-11T03:37:20.000Z
4,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,0.999616,72224423782,5,72219476624,8240571576,1.000000,...,7.223711e+10,NaN,1.043000,-4.20226,2018-11-14T16:00:00.000Z,0.877647,1.389727e+01,2023-03-11T00:02:13.000Z,None,2026-08-11T03:37:20.000Z
5,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.013000,63327234863,6,101255118073,988875287,1.039000,...,9.998564e+10,1.000000e+11,3.650000,-72.22637,2025-07-17T19:40:53.000Z,0.002686,3.760118e+04,2014-05-21T16:00:00.000Z,None,2026-08-11T03:37:20.000Z
6,solana,sol,Solana,https://coin-images.coingecko.com/coins/images...,76.080000,44312332464,7,48080181334,1334640618,77.070000,...,6.320099e+08,NaN,293.310000,-74.06206,2025-01-19T03:15:27.000Z,0.500801,1.509147e+04,2020-05-11T11:35:23.000Z,None,2026-08-11T03:37:20.000Z
7,tron,trx,TRON,https://coin-images.coingecko.com/coins/images...,0.331001,31410105051,8,31410354783,373327404,0.331643,...,9.489836e+10,NaN,0.431288,-23.25298,2024-12-03T16:10:40.000Z,0.001804,1.824469e+04,2017-11-11T16:00:00.000Z,"{'times': 173.1728703050978, 'currency': 'usd'...",2026-08-11T03:37:20.000Z
8,figure-heloc,figr_heloc,Figure Heloc,https://coin-images.coingecko.com/coins/images...,1.003000,21140202274,9,21140202274,53014149,1.041000,...,2.108249e+10,NaN,1.061000,-5.44703,2026-08-03T14:19:20.000Z,0.155357,5.454628e+02,2025-10-31T06:27:24.000Z,None,2026-08-11T03:37:20.000Z
9,hyperliquid,hype,Hyperliquid,https://coin-images.coingecko.com/coins/images...,55.260000,12292761640,10,55252743222,247953125,56.020000,...,9.553071e+08,1.000000e+09,76.870000,-28.10703,2026-06-16T13:00:30.000Z,3.810000,1.350913e+03,2024-11-29T01:30:30.000Z,None,2026-08-11T03:37:20.000Z

In [16]:
df.shape

(10, 26)

In [17]:
df.columns.tolist()

['id',
 'symbol',
 'name',
 'image',
 'current_price',
 'market_cap',
 'market_cap_rank',
 'fully_diluted_valuation',
 'total_volume',
 'high_24h',
 'low_24h',
 'price_change_24h',
 'price_change_percentage_24h',
 'market_cap_change_24h',
 'market_cap_change_percentage_24h',
 'circulating_supply',
 'total_supply',
 'max_supply',
 'ath',
 'ath_change_percentage',
 'ath_date',
 'atl',
 'atl_change_percentage',
 'atl_date',
 'roi',
 'last_updated']

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                10 non-null     str
 1   symbol                            10 non-null     str
 2   name                              10 non-null     str
 3   image                             10 non-null     str
 4   current_price                     10 non-null     float64
 5   market_cap                        10 non-null     int64
 6   market_cap_rank                   10 non-null     int64
 7   fully_diluted_valuation           10 non-null     int64
 8   total_volume                      10 non-null     int64
 9   high_24h                          10 non-null     float64
 10  low_24h                           10 non-null     float64
 11  price_change_24h                  9 non-null      float64
 12  price_change_percentage_24h       10 non-null     float64
 13  market_cap_change_24h             9 non-null      float64
 14  market_cap_change_percentage_24h  9 non-null      float64
 15  circulating_supply                10 non-null     float64
 16  total_supply                      10 non-null     float64
 17  max_supply                        4 non-null      float64
 18  ath                               10 non-null     float64
 19  ath_change_percentage             10 non-null     float64
 20  ath_date                          10 non-null     str
 21  atl                               10 non-null     float64
 22  atl_change_percentage             10 non-null     float64
 23  atl_date                          10 non-null     str
 24  roi                               2 non-null      object
 25  last_updated                      10 non-null     str
dtypes: float64(14), int64(4), object(1), str(7)
memory usage: 2.2+ KB

In [19]:
selected_columns = [
    "id",
    "symbol",
    "name",
    "current_price",
    "market_cap",
    "market_cap_rank",
    "total_volume",
    "high_24h",
    "low_24h",
    "price_change_24h",
    "price_change_percentage_24h",
    "circulating_supply",
    "total_supply",
    "max_supply",
    "ath",
    "ath_change_percentage",
    "ath_date",
    "last_updated"
]
df = df[selected_columns]

In [20]:
df.columns

Index(['id', 'symbol', 'name', 'current_price', 'market_cap',
       'market_cap_rank', 'total_volume', 'high_24h', 'low_24h',
       'price_change_24h', 'price_change_percentage_24h', 'circulating_supply',
       'total_supply', 'max_supply', 'ath', 'ath_change_percentage',
       'ath_date', 'last_updated'],
      dtype='str')

In [21]:
df.shape

(10, 18)

In [22]:
df.head()

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,high_24h,low_24h,price_change_24h,price_change_percentage_24h,circulating_supply,total_supply,max_supply,ath,ath_change_percentage,ath_date,last_updated
0,bitcoin,btc,Bitcoin,64076.000000,1285945024366,1,20417791024,65317.000000,63771.000000,-913.113218,-1.7,2.006855e+07,2.006858e+07,21000000.0,126080.000,-49.17808,2025-10-06T10:57:42.000Z,2026-08-11T03:37:20.000Z
1,ethereum,eth,Ethereum,1878.750000,226738675664,2,7009662322,1928.940000,1867.610000,-40.037432,-2.3,1.206820e+08,1.206820e+08,NaN,4946.050,-62.01502,2025-08-24T11:21:03.000Z,2026-08-11T03:37:20.000Z
2,tether,usdt,Tether,0.999123,183090218119,3,32917405107,0.999842,0.998973,-0.000226,0.0,1.832459e+11,1.887129e+11,NaN,1.320,-24.48591,2018-07-23T16:00:00.000Z,2026-08-11T03:37:20.000Z
3,binancecoin,bnb,BNB,599.830000,79877019560,4,512205854,606.000000,597.290000,-2.099794,-0.6,1.331643e+08,1.331643e+08,200000000.0,1369.990,-56.21672,2025-10-13T00:41:24.000Z,2026-08-11T03:37:20.000Z
4,usd-coin,usdc,USDC,0.999616,72224423782,5,8240571576,1.000000,0.999435,-0.000048,0.0,7.224971e+10,7.223711e+10,NaN,1.043,-4.20226,2018-11-14T16:00:00.000Z,2026-08-11T03:37:20.000Z

In [23]:
df.isnull().sum()

id                             0
symbol                         0
name                           0
current_price                  0
market_cap                     0
market_cap_rank                0
total_volume                   0
high_24h                       0
low_24h                        0
price_change_24h               1
price_change_percentage_24h    0
circulating_supply             0
total_supply                   0
max_supply                     6
ath                            0
ath_change_percentage          0
ath_date                       0
last_updated                   0
dtype: int64

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           10 non-null     str
 1   symbol                       10 non-null     str
 2   name                         10 non-null     str
 3   current_price                10 non-null     float64
 4   market_cap                   10 non-null     int64
 5   market_cap_rank              10 non-null     int64
 6   total_volume                 10 non-null     int64
 7   high_24h                     10 non-null     float64
 8   low_24h                      10 non-null     float64
 9   price_change_24h             9 non-null      float64
 10  price_change_percentage_24h  10 non-null     float64
 11  circulating_supply           10 non-null     float64
 12  total_supply                 10 non-null     float64
 13  max_supply                   4 non-null      float64
 14  ath                          10 non-null     float64
 15  ath_change_percentage        10 non-null     float64
 16  ath_date                     10 non-null     str
 17  last_updated                 10 non-null     str
dtypes: float64(10), int64(3), str(5)
memory usage: 1.5 KB

In [25]:
df["ath_date"] = pd.to_datetime(df["ath_date"], utc=True)
df["last_updated"] = pd.to_datetime(df["last_updated"], utc=True)

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           10 non-null     str
 1   symbol                       10 non-null     str
 2   name                         10 non-null     str
 3   current_price                10 non-null     float64
 4   market_cap                   10 non-null     int64
 5   market_cap_rank              10 non-null     int64
 6   total_volume                 10 non-null     int64
 7   high_24h                     10 non-null     float64
 8   low_24h                      10 non-null     float64
 9   price_change_24h             9 non-null      float64
 10  price_change_percentage_24h  10 non-null     float64
 11  circulating_supply           10 non-null     float64
 12  total_supply                 10 non-null     float64
 13  max_supply                   4 non-null      float64
 14  ath                          10 non-null     float64
 15  ath_change_percentage        10 non-null     float64
 16  ath_date                     10 non-null     datetime64[us, UTC]
 17  last_updated                 10 non-null     datetime64[us, UTC]
dtypes: datetime64[us, UTC](2), float64(10), int64(3), str(3)
memory usage: 1.5 KB

In [27]:
df["extracted_at"] = pd.Timestamp.now(tz="UTC")

In [28]:
df[["name", "last_updated", "extracted_at"]].head()

       name              last_updated                     extracted_at
0   Bitcoin 2026-08-11 03:37:20+00:00 2026-08-11 03:39:42.358990+00:00
1  Ethereum 2026-08-11 03:37:20+00:00 2026-08-11 03:39:42.358990+00:00
2    Tether 2026-08-11 03:37:20+00:00 2026-08-11 03:39:42.358990+00:00
3       BNB 2026-08-11 03:37:20+00:00 2026-08-11 03:39:42.358990+00:00
4      USDC 2026-08-11 03:37:20+00:00 2026-08-11 03:39:42.358990+00:00

In [29]:
df.columns

Index(['id', 'symbol', 'name', 'current_price', 'market_cap',
       'market_cap_rank', 'total_volume', 'high_24h', 'low_24h',
       'price_change_24h', 'price_change_percentage_24h', 'circulating_supply',
       'total_supply', 'max_supply', 'ath', 'ath_change_percentage',
       'ath_date', 'last_updated', 'extracted_at'],
      dtype='str')

In [30]:
df = df.rename(columns={
    "id": "coin_id",
    "name": "coin_name",
    "current_price": "current_price_usd",
    "market_cap": "market_cap_usd",
    "total_volume": "total_volume_usd",
    "high_24h": "high_24h_usd",
    "low_24h": "low_24h_usd",
    "price_change_24h": "price_change_24h_usd",
    "ath": "ath_usd",
    "last_updated": "source_updated_utc"
})

In [31]:
df.columns

Index(['coin_id', 'symbol', 'coin_name', 'current_price_usd', 'market_cap_usd',
       'market_cap_rank', 'total_volume_usd', 'high_24h_usd', 'low_24h_usd',
       'price_change_24h_usd', 'price_change_percentage_24h',
       'circulating_supply', 'total_supply', 'max_supply', 'ath_usd',
       'ath_change_percentage', 'ath_date', 'source_updated_utc',
       'extracted_at'],
      dtype='str')

In [32]:
df = df.rename(columns={
    "extracted_at": "extracted_at_utc"
})

In [33]:
df.head()

,coin_id,symbol,coin_name,current_price_usd,market_cap_usd,market_cap_rank,total_volume_usd,high_24h_usd,low_24h_usd,price_change_24h_usd,price_change_percentage_24h,circulating_supply,total_supply,max_supply,ath_usd,ath_change_percentage,ath_date,source_updated_utc,extracted_at_utc
0,bitcoin,btc,Bitcoin,64076.000000,1285945024366,1,20417791024,65317.000000,63771.000000,-913.113218,-1.7,2.006855e+07,2.006858e+07,21000000.0,126080.000,-49.17808,2025-10-06 10:57:42+00:00,2026-08-11 03:37:20+00:00,2026-08-11 03:39:42.358990+00:00
1,ethereum,eth,Ethereum,1878.750000,226738675664,2,7009662322,1928.940000,1867.610000,-40.037432,-2.3,1.206820e+08,1.206820e+08,NaN,4946.050,-62.01502,2025-08-24 11:21:03+00:00,2026-08-11 03:37:20+00:00,2026-08-11 03:39:42.358990+00:00
2,tether,usdt,Tether,0.999123,183090218119,3,32917405107,0.999842,0.998973,-0.000226,0.0,1.832459e+11,1.887129e+11,NaN,1.320,-24.48591,2018-07-23 16:00:00+00:00,2026-08-11 03:37:20+00:00,2026-08-11 03:39:42.358990+00:00
3,binancecoin,bnb,BNB,599.830000,79877019560,4,512205854,606.000000,597.290000,-2.099794,-0.6,1.331643e+08,1.331643e+08,200000000.0,1369.990,-56.21672,2025-10-13 00:41:24+00:00,2026-08-11 03:37:20+00:00,2026-08-11 03:39:42.358990+00:00
4,usd-coin,usdc,USDC,0.999616,72224423782,5,8240571576,1.000000,0.999435,-0.000048,0.0,7.224971e+10,7.223711e+10,NaN,1.043,-4.20226,2018-11-14 16:00:00+00:00,2026-08-11 03:37:20+00:00,2026-08-11 03:39:42.358990+00:00

In [34]:
import os
from dotenv import load_dotenv
from pathlib import Path

In [35]:
env_path = Path("../.env")
load_dotenv(env_path)

True

In [36]:
print(os.getenv("DB_HOST"))
print(os.getenv("DB_PORT"))
print(os.getenv("DB_NAME"))
print(os.getenv("DB_USER"))

localhost
5432
crypto_pipeline
postgres

In [37]:
from pathlib import Path

env_path = Path("../.env")
print(env_path.resolve())
print(env_path.exists())

C:\Users\Muñoz\OneDrive\Desktop\crypto-etl-pipeline\.env
True

In [38]:
from dotenv import load_dotenv

load_dotenv(dotenv_path=env_path, override=True)

True

In [39]:
from sqlalchemy import create_engine, URL, text

In [40]:
db_host = os.getenv("DB_HOST")
db_port = os.getenv("DB_PORT")
db_name = os.getenv("DB_NAME")
db_user = os.getenv("DB_USER")
db_password = os.getenv("DB_PASSWORD")

In [41]:
database_url = URL.create(
    drivername="postgresql+psycopg2",
    username=db_user,
    password=db_password,
    host=db_host,
    port=int(db_port),
    database=db_name
)

In [42]:
#ERROR engine = create_engine(database_url)

In [43]:
import sys
print(sys.executable)

c:\Users\Muñoz\AppData\Local\Programs\Python\Python313\python.exe

In [44]:
%pip install "psycopg[binary]"

Requirement already satisfied: psycopg[binary] in c:\Users\Muñoz\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.3.4)
Requirement already satisfied: tzdata in c:\Users\Muñoz\AppData\Local\Programs\Python\Python313\Lib\site-packages (from psycopg[binary]) (2026.3)
Requirement already satisfied: psycopg-binary==3.3.4 in c:\Users\Muñoz\AppData\Local\Programs\Python\Python313\Lib\site-packages (from psycopg[binary]) (3.3.4)
Note: you may need to restart the kernel to use updated packages.

In [45]:
%pip uninstall -y psycopg psycopg-binary

Found existing installation: psycopg 3.3.4
Uninstalling psycopg-3.3.4:
  Successfully uninstalled psycopg-3.3.4
Found existing installation: psycopg-binary 3.3.4
Uninstalling psycopg-binary-3.3.4:
  Successfully uninstalled psycopg-binary-3.3.4
Note: you may need to restart the kernel to use updated packages.

In [46]:
%pip install --no-cache-dir "psycopg[binary]"

Collecting psycopg[binary]
  Downloading psycopg-3.3.4-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: tzdata in c:\Users\Muñoz\AppData\Local\Programs\Python\Python313\Lib\site-packages (from psycopg[binary]) (2026.3)
Collecting psycopg-binary==3.3.4 (from psycopg[binary])
  Downloading psycopg_binary-3.3.4-cp313-cp313-win_amd64.whl.metadata (2.7 kB)
Downloading psycopg-3.3.4-py3-none-any.whl (213 kB)
Downloading psycopg_binary-3.3.4-cp313-cp313-win_amd64.whl (3.6 MB)
   ---------------------------------------- 0.0/3.6 MB ? eta -:--:--
   -------------------------- ------------- 2.4/3.6 MB 11.8 MB/s eta 0:00:01
   ---------------------------------------- 3.6/3.6 MB 11.9 MB/s  0:00:00
Installing collected packages: psycopg-binary, psycopg

   ---------------------------------------- 0/2 [psycopg-binary]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   ---------------------------------------- 2/2 [psycopg]

Successfully installed psycopg-3.3.4 psycopg-binary-3.3.4
Note: you may need to restart the kernel to use updated packages.

In [47]:
import psycopg

print(psycopg.__version__)

3.3.4

In [48]:
df.columns

Index(['coin_id', 'symbol', 'coin_name', 'current_price_usd', 'market_cap_usd',
       'market_cap_rank', 'total_volume_usd', 'high_24h_usd', 'low_24h_usd',
       'price_change_24h_usd', 'price_change_percentage_24h',
       'circulating_supply', 'total_supply', 'max_supply', 'ath_usd',
       'ath_change_percentage', 'ath_date', 'source_updated_utc',
       'extracted_at_utc'],
      dtype='str')

In [49]:
import os
from pathlib import Path
from dotenv import load_dotenv
from sqlalchemy import create_engine, URL

env_path = Path("../.env")
load_dotenv(dotenv_path=env_path)

db_host = os.getenv("DB_HOST")
db_port = os.getenv("DB_PORT")
db_name = os.getenv("DB_NAME")
db_user = os.getenv("DB_USER")
db_password = os.getenv("DB_PASSWORD")

database_url = URL.create(
    drivername="postgresql+psycopg",
    username=db_user,
    password=db_password,
    host=db_host,
    port=int(db_port),
    database=db_name
)


engine = create_engine(database_url)

In [50]:
engine

Engine(postgresql+psycopg://postgres:***@localhost:5432/crypto_pipeline)

In [52]:
from sqlalchemy import MetaData, Table

metadata = MetaData()

crypto_market_history = Table(
    "crypto_market_history",
    metadata,
    autoload_with=engine
)

In [53]:
from sqlalchemy.dialects.postgresql import insert

records = df.to_dict(orient="records")

with engine.begin() as connection:
    stmt = insert(crypto_market_history).values(records)

    stmt = stmt.on_conflict_do_nothing(
        index_elements=["coin_id", "extracted_at_utc"]
    )

    result = connection.execute(stmt)

    print(f"Rows inserted: {result.rowcount}")

Rows inserted: -1